### ISSUE TITLE
Null Safety support

### ISSUE THREAD

**Issue by woelmer** [Vanethos/flutter_version_banner#2]
Any plans on supporting null safety?

**Comment by corentingiraud** [comment]
I've opened [a PR](https://github.com/Vanethos/flutter_version_banner/pull/3).
Use my fork as a workaround for now:

```
  version_banner:
    git:
      url: https://github.com/corentingiraud/flutter_version_banner
      ref: master
```
